### ISSUE TITLE
Please help clarifying the docs

### ISSUE THREAD

**Issue by BerndGewehr** [Factor-y/ConnectionsCloudHowTo#1]
Hi Daniele,

thank you for making this available.

The magic undocumented thing is
    
      "path": "A._myorg",

Is there a doc where these magic words come from? Did you find a link?

Also the order value to add some new items seems not to be absolutely clear, the docs say 1.500 and use 35 in the (not working) example json.

Thank you!

**Comment by BerndGewehr** [comment]
Found a working one for adding a menu completely left:

    {
  "extensions": [
    {
      "applications": [
        "topMenuPortalLink"
      ],
      "path": "com.ibm.navbar.order.35",
      "title": "Portal",
      "ext_id": "de.voessing.topmenu.portal.link",
      "type": "com.ibm.action.link",
      "name": "Portal",
      "id": "0c589b75-0e60-4273-b3b5-24ab72dbc65c",
      "payload": {
        "link": "http://portal.voessing.de"
      }
    }
  ],
  "title": "topMenuPortalLink",
  "icon": "",
  "app_id": "de.voessing.topmenu.portal.app",
  "name": "topMenuPortalLink",
  "id": "a1737842-6b3a-487b-9931-e456fbe07870",
  "services": [
    "TopNavigationBar"
  ],
  "url": "http://www.voessing.de"
}

**Comment by DanieleVistalli** [comment]
Hello Bernd, I've added a "Slack" item and documented the "undocumented" icon attribute for toplevel menus.

I'm going to add a "full-list" of order values and other undocumented items.

**Comment by DanieleVistalli** [comment]
@BerndGewehr is the now doc useful to you. I'd close this issue. If you've specific questions please open as new requests.

**Comment by BerndGewehr** [comment]
OK, thanks a lot!
