### ISSUE TITLE
Secret names of menu items

### ISSUE THREAD

**Issue by BerndGewehr** [Factor-y/ConnectionsCloudHowTo#2]
In your example you used A._myorg which is the organization menu item most left in the header bar.

I wondered if you have a source of documentation für this and other names to use them in heavy modifying of the header bar?

E. G.:
A._communities?
A._mail?
A._calendar?
A._home?

**Comment by DanieleVistalli** [comment]
Start looking here for communities:

https://github.com/Factor-y/ConnectionsCloudHowTo/blob/master/cloud/extensions/navigationbar/CommunitiesNoDropDown.json

**Comment by DanieleVistalli** [comment]
@BerndGewehr served...

Docs has moved also: https://github.com/Factor-y/ConnectionsCloudHowTo/blob/master/cloud/extensions/navigationbar/README.md

**Comment by BerndGewehr** [comment]
Great, thank you!
