### ISSUE TITLE
Bell and chat bubble disappear on "partner" version of header bar

### ISSUE THREAD

**Issue by BerndGewehr** [Factor-y/ConnectionsCloudHowTo#3]
The wonderful function of being alerted on chat and action required items in the Connections header bar gets lost once you use the third party version of the header using the .../partner/... URL.

If you do not use that URL but use .../myapp/... the icons stay but do not work.

Die you find a way to have a complete Connections cloud header bar in a third party app including bell and bubble?

**Comment by DanieleVistalli** [comment]
I've not found a way.

The bell opens an iFrame that should point to the cloud server and is then not working as it tries to load the "notification" from the server embedding the app.

As we're going to get Connections 6.0 in a very short timeframe (and with it the new Activity center) I've not spent time trying to figure this out.

We'll look into it once we are on Connections Green.

**Comment by BerndGewehr** [comment]
All right so we wait for the new action center and then check again for 3rd party compatibility! Thank you!
